server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: http://localhost:8081/
          predicates:
            - Path=/employee/**

        - id: consumerModule
          uri: http://localhost:8082/
          predicates:
            - Path=/consumer/**

        - id: hrModule
          uri: http://localhost:8201/
          predicates:
            - Path=/hr/**

        - id: pathologyModule
          uri: http://localhost:8200/
          predicates:
            - Path=/pathology/**
